[package]
name = "mulnictl"
version = "0.1.0"
edition = "2021"

[lib]
name = "mulnictl"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["charset", "json", "blocking"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21" }
ndk = { version = "0.9", features = ["api-level-26"] }
ndk-sys = { version = "0.6" }
